# The migration codes

from django.db import migrations


CREATE_TABLES_SQL = """
CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee_work_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT work_shift_end_after_start CHECK (end_time > start_time)
);

CREATE INDEX employee_work_shift_employee_id_idx
    ON employee_work_shift(employee_id);

CREATE INDEX employee_work_shift_time_idx
    ON employee_work_shift(employee_id, start_time, end_time);
"""

DROP_TABLES_SQL = """
DROP TABLE IF EXISTS employee_work_shift;
DROP TABLE IF EXISTS employee;
"""


class Migration(migrations.Migration):
    initial = True

    """
    indicates what other migration must be ran before this one 
    [
        ("employee", "0001_initial"),
        ("another_app", "0003_something"),
    ]
    """
    dependencies: list[tuple[str, str]] = []
    """
    The list of operations that  that are written above 
    """
    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLES_SQL,
            reverse_sql=DROP_TABLES_SQL,
        )
    ]
