from django.db import migrations

CREATE_TABLE_SQL = """
CREATE TABLE employees_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL
        REFERENCES employee(id)
        ON DELETE CASCADE,
    role_name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employees_roles_employee_role_unique
        UNIQUE (employee_id, role_name)
);

CREATE INDEX employees_roles_employee_id_idx
    ON employees_roles(employee_id);
"""

DROP_TABLE_SQL = """
DROP TABLE IF EXISTS employees_roles;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLE_SQL,
            reverse_sql=DROP_TABLE_SQL,
        ),
    ]
